/**
 * Generated by '@kontent-ai/model-generator@5.2.0'
 *
 * Project name: Sample Project
 * Environment: Production
 * Project Id: 3ba36257-ccc7-0023-c48e-d2ece553dd07
 */
export const assetFolders = {
  /**
   * Café locations
   */
  caféLocations: {
    id: '958001d8-2228-4373-b966-5262b5b96f71',
    name: 'Café locations',
    externalId: undefined,
    folders: {},
  },
};
