/**
 * Generated by '@kontent-ai/model-generator@5.2.0'
 *
 * Project name: Sample Project
 * Environment: Production
 * Project Id: 3ba36257-ccc7-0023-c48e-d2ece553dd07
 */
export const collections = {
  /**
   * Default
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
};
